version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src  
    working_dir: /src/compra_agora_scrapy/compra_agora_scrapy/spiders

    tty: true  
