
version: "3.8"
services:
  extracao_dados_app:
    build:
      context: ./Questao_1/extracao_dados
      dockerfile: Dockerfile
    volumes:
      - ./Questao_1/extracao_dados/src:/src  
    working_dir: /src/compra_agora_scrapy/compra_agora_scrapy/spiders
    tty: true  


  login_app:
    build:
      context: ./Questao_1/login
      dockerfile: Dockerfile
    volumes:
      - ./Questao_1/login/src:/src  
    working_dir: /src
    tty: true
