FROM python:3.11-slim

WORKDIR /src/

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

WORKDIR /src/

CMD ["python", "main.py"]
#caso queria acessar o cmd do container substituir por: 
    # CMD ["tail", "-f", "/dev/null"]
# e  usar o comando:    
    # docker exec -it <nome_do_container> bash
